Added Confirmation Before Delete Task
shacker/django-todo pull request #113
Opened 2021-01-30 07:22 UTC by 1hanzla100

2021-01-30 07:23 UTC, 1hanzla100 commented
@shacker  Review Pull Request and Merge it with master branch

2021-02-03 07:03 UTC, shacker commented on todo/templates/todo/task_detail.html
> +              <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Are you sure to delete task?');" name="submit_delete">
Please make it say "Are you sure you want to delete this task?"

2021-02-03 07:04 UTC, shacker requested changes
Hi - Can you please make the language change requested, and also post a couple of screenshots in the PR description, showing what happens when you click either of the two buttons? (as proof that it does delete what it should delete, and doesn't delete if you cancel out). Thanks.

2021-03-21 20:34 UTC, shacker commented
@1hanzla100 We never heard back from after the code review above. Did you still want to have this merged? Please respond.

2021-03-21 21:09 UTC, shacker commented
@1hanzla100 Nevermind, I'll just bring it in and change it myself. Thanks!

2021-03-21 21:10 UTC, merged