Connect users tracked mail
shacker/django-todo pull request #116
Opened 2021-02-16 20:22 UTC by fross123

I tweaked one of the logs for the tracker because it was failing a test. Hopefully it still logs what you need, I apologize if it doesn't.

Also, the feature discussed in #112. It works well in my pretty limited situation. I wound up adding a setting and only matching if settings.TODO_MATCH_USERS is true to make sure that current users would not be affected unnecessarily.

Thanks!

2021-04-23 10:02 UTC, multun requested changes
Thanks for your contribution :+1:

It looks good to me overall, I've requested a few changes.
Out of curiosity, are you using the mail tracker in production somewhere? If so, are you happy with the experience?

2021-09-29 00:08 UTC, bernd-wechner commented on todo/mail/consumers/tracker.py
> +        logger.info(f"found an answer thread: {answer_thread}")
That link is broken. I'd be interested to know the reasoning behind a preference against f-strings.

2021-09-29 05:27 UTC, shacker commented on todo/mail/consumers/tracker.py
> +        logger.info(f"found an answer thread: {answer_thread}")
@bernd-wechner The link works for me. The article makes a good point, though I have to see we use f-strings in logging at work and have never been bitten by that issue, which I consider an edge case.

2021-09-29 05:28 UTC, shacker commented
@fross123 - @multun Did a code review on this last April, and I was just wondering if you were going to be able to follow up on his comments?

2021-09-29 05:48 UTC, bernd-wechner commented on todo/mail/consumers/tracker.py
> +        logger.info(f"found an answer thread: {answer_thread}")
Cool. that site doesn't use DNSEC and blocked here, so I used a proxy. The point the it makes is valid for high volume logging. The rate at which todo is used here (or likely ever to be on a given site) makes the noted issues irrelevant beyond simply being better practice in general for logging (as some of it is high volume and frequency or logging things expensive to calculate). But all good, I now understand the concern.

2021-10-11 23:40 UTC, shacker commented
@fross123 Definitely still interested in having the PR, if you feel like it's close and you're willing!

2021-11-02 15:38 UTC, fross123 commented on todo/mail/consumers/tracker.py
> +            user = None
Absolutely!

2021-11-02 15:38 UTC, fross123 commented on todo/mail/consumers/tracker.py
> +                created_by=user,
Ooh yeah! Will do this.

2021-11-02 15:45 UTC, fross123 commented on README.md
> +TODO_MATCH_USERS = True # Set to True if you would like to match users. If you do not have authentication setup, do not set this to True.
Totally hear you on the external authentication. However, I am a little unclear on what the setting should be when we want to use this function, could you expand on that? Where would `get_django_users_by_email` need to be and what should it do?

Also, I will change the name of the option!

2021-11-02 15:45 UTC, fross123 commented on README.md
> +Optionally, you can match incoming users with their accounts.
Love it, thank you!

2021-11-02 20:00 UTC, fross123 commented
Sorry about the delay in this folks. I've pushed some updates, let me know what you think. Wasn't too sure about the change requested to the setting, so I will update when we discuss that further.

Thanks!

2022-03-05 23:46 UTC, shacker commented on todo/mail/consumers/tracker.py
> +    if not settings.TODO_MAIL_USER_MAPPER:
Nice.

2022-03-05 23:46 UTC, shacker commented on todo/tests/test_tracker.py
> +    Ensure that a user is added to new lists when sent from registered email
Thanks for adding a test!

2022-03-05 23:47 UTC, shacker approved these changes
LGTM, and apologies for the lengthy response delay. Approved and merging. Cheers!

2022-03-05 23:47 UTC, merged